style.css のグループ分けとインデントの修正
comozilla/comozilla-paper pull request #11
Opened 2016-12-05 06:03 UTC by mk7087

2016-12-05 06:27 UTC, shundroid requested changes

2016-12-05 06:27 UTC, shundroid commented on style.css
> +  text-align:center;
あ、`:` のあとにスペースを入れていって

2016-12-05 06:27 UTC, shundroid commented on style.css
> +  background:-moz-linear-gradient(top,#70caf20%,#181b47100%);
ここは`,` のあとにスペースを入れて

2016-12-05 06:27 UTC, shundroid commented on style.css
> +  text-align:center;
他全部よろしく

2016-12-05 06:27 UTC, shundroid commented
@mk7087 レビューしたからよろしく

2016-12-05 06:36 UTC, shundroid requested changes

2016-12-05 06:36 UTC, shundroid commented on style.css
> +body{
あ、`{` の前にもスペース入れて

2016-12-05 06:36 UTC, shundroid commented on style.css
> +body{
全部よろしく

2016-12-05 06:36 UTC, shundroid commented on style.css
> +  background: -moz-linear-gradient(top, #70caf20%, #181b47100%);
ここは書き方が古いっす

https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Using_CSS_gradients

これを参考にして

```css
background: linear-gradient(to bottom, #70caff 20%, #181b47 100%)
```

こんな感じかな

2016-12-05 06:36 UTC, shundroid commented on style.css
> +  color: #ffffff;
ここはこう書けます

```css
color: #fff;
```

2016-12-05 06:36 UTC, shundroid commented on style.css
> +  color: #ffffff;
というか、`color: white` のほうが適切だわ

2016-12-05 06:36 UTC, shundroid commented on style.css
> +  color: #ffffff;
ここも `color: white` にして

2016-12-05 06:37 UTC, shundroid commented
@mk7087 よろ

2016-12-05 06:38 UTC, dadaa commented on style.css
> +#headh1{
どうもありがとうございます！＆はじめまして！
私も少しレビューしてみます。

ここ headh1 の id を持つエレメントが index.html には無いようです。
`#head h1` でいけそうです。

2016-12-05 06:38 UTC, dadaa commented on style.css
> +#head{
ヘッダ的な意味を表したいとするならば、header 要素を使うと良いかと思います。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/header

2016-12-05 06:38 UTC, dadaa commented on style.css
> +.h1address{
html 内で class を振らずとも、
`#divaddress h1`
で指定できそうです。

2016-12-05 06:38 UTC, dadaa commented on style.css
> +#head{
その他にも main や section, footer などがあるので、文書内での意味付けに使ってみると良いかと思います。

2016-12-05 06:39 UTC, shundroid commented
@dadaa ありがとうございます！

2016-12-05 06:44 UTC, shundroid commented
@mk7087 あ、あと直すとこほかにもあるからよろしく

https://github.com/comozilla/open-exwec
あと、これなに？

2016-12-05 06:48 UTC, mk7087 commented
open-exwec削除しますか？

2016-12-05 06:48 UTC, shundroid commented
@mk7087 
> open-exwec削除しますか？
いや、なにかがしりたい

2016-12-05 06:53 UTC, mk7087 commented
extensible web conversation
要は会話ツール(未完成)をアップしようとしている

2016-12-05 06:53 UTC, shundroid commented
@mk7087 ああなるほど

そうだね、それだったら comozilla アカウントじゃなくて、
個人の mk7087 のほうのリポジトリとして作ったほうがいいと思う

2016-12-05 06:57 UTC, mk7087 commented
> そうだね、それだったら comozilla アカウントじゃなくて、
> 個人の mk7087 のほうのリポジトリとして作ったほうがいいと思う

移動しました

2016-12-05 06:58 UTC, shundroid commented
@mk7087 ありがとー
それでもしレビューとかが必要だったら、同じようにできるのでそれでお願いします

あと、↑でやっていないことがまだあるので、それお願い

2016-12-05 06:59 UTC, shundroid commented
あとちょっと落ちます

2016-12-05 07:19 UTC, dadaa commented on index.html
> +      <div id="head">
どうもありがとうございます！
たぶん、この div の代わりに header を使う感じで良いかと思います。

`<header>`
`  <img src="logo.png">`
...

みたいに。
これにあわせて、CSS も
`header {`
`  background: -moz-linear-gradient(top, #70caf20%, #181b47100%);`
`}`
な感じにすると良いかと思います。

2016-12-05 07:19 UTC, dadaa commented on index.html
> +      <div id="description">
ここも同様ですね。
`<section id="description">`
とかで良いかと思います。

2016-12-05 07:19 UTC, dadaa commented on index.html
> +      <div id="text">
ここも同様です。

2016-12-05 07:19 UTC, dadaa commented on index.html
> +      <div id="divaddress">
同様です。
divaddress という id も削ってしまって良いかと思います。

2016-12-05 07:28 UTC, dadaa commented on style.css
> +footer #qr {
id はドキュメント中でユニークになりますので、この書き方ですと正常に動くのですが、ブラウザ的に少しだけ無駄な処理をしてしまいます。
ここは単純に
`#qr`
あるいは、qr の id を index.html から削除して
`footer img`
でも良さそうです。

2016-12-05 08:19 UTC, dadaa commented on index.html
>        <img src="qr.png" id="qr" />
`footer img`
の CSS の指定ですと、id="qr" は削除して良いかと思います。

2016-12-05 08:19 UTC, dadaa commented on index.html
> +      <h1>コモジラ研究所</h1><br />
下に余白などを求めたいときは br ではなく、スタイルで行った方が良いと思います。
たとえば、margin-bottom とか。

2016-12-05 08:23 UTC, mk7087 commented on index.html
> +      <h1>コモジラ研究所</h1><br />
余白ではないです

2016-12-05 09:12 UTC, dadaa commented on index.html
> +      <h1>コモジラ研究所</h1><br />
あれ？ h1 ってもともと改行されませんでしたっけ？
なので br で改めて改行しているの理由は何かしら？

2016-12-05 09:15 UTC, mk7087 commented on index.html
> +      <h1>コモジラ研究所</h1><br />
CSS見ると分かると思いますがdisplay:inline;にしています

2016-12-05 09:16 UTC, dadaa commented on index.html
> +      <h1>コモジラ研究所</h1><br />
うん、そうみたいですね。
そしたら、そこの display: inline の指定を削除すれば、br 要らないんじゃないですか？

2016-12-05 09:17 UTC, mk7087 commented on index.html
> +      <h1>コモジラ研究所</h1><br />
位置の関係です

2016-12-05 09:18 UTC, mk7087 commented on index.html
> +      <h1>コモジラ研究所</h1><br />
Fx devで調整しますのでお待ちください

2016-12-05 09:19 UTC, dadaa commented on index.html
> +      <h1>コモジラ研究所</h1><br />
位置関係はスタイルでいじった方が良いですよ？

2016-12-05 09:21 UTC, mk7087 commented on index.html
> +      <h1>コモジラ研究所</h1><br />
ですからCSSをFx devで調整します

2016-12-05 10:36 UTC, shundroid commented on index.html
> +    <link rel="styleheet" href="style.css" />
ちょちょ、`styleheet` になってるよ
動作確認した？

2016-12-05 10:38 UTC, mk7087 commented on index.html
> +    <link rel="styleheet" href="style.css" />
OK。それが正しい

2016-12-05 10:40 UTC, shundroid commented
@mk7087 
あと、今この PR は、`style.css のグループ分けとインデントの修正` でやっているから、
例えば、「imgにaltを追加」とかになっちゃうと、内容が違ってきて、あとでわかりにくくなっちゃう。

だから、ブランチを分けて別の PR として出してください

2016-12-05 10:42 UTC, mk7087 commented
やり方教えて

2016-12-05 10:42 UTC, shundroid commented
@mk7087 
- スタイルで h1 の下に余白を作る方法
- ブランチを分ける方法

どっち？

2016-12-05 10:43 UTC, mk7087 commented
ブランチを分ける方法

2016-12-05 10:45 UTC, shundroid commented
https://git-scm.com/

コマンドラインからならわかる

```
git checkout -b <ブランチ名（例：fix-index-html）>
```

わかんなかったら、今回はそのままでいいので、
今後そうしてください

2016-12-05 22:20 UTC, mk7087 commented
今のところ必要な修正を確認

2016-12-06 05:12 UTC, shundroid commented
@mk7087 
> ですからCSSをFx devで調整します

この件はすぐできそう？

2016-12-06 06:05 UTC, mk7087 commented
push accessって．．．?

2016-12-06 06:06 UTC, shundroid commented
@mk7087 どうした？

2016-12-06 06:07 UTC, mk7087 commented
push accessって何をすれば？

2016-12-06 06:08 UTC, shundroid commented
どこでエラーが出てるの？

2016-12-06 06:12 UTC, mk7087 commented
pull requesut出した後のpush?のやり方わからない

2016-12-06 06:15 UTC, shundroid commented
ブランチ消した？
なんか unknown repository になってる

2016-12-06 06:16 UTC, mk7087 commented
？
不明

2016-12-06 06:16 UTC, mk7087 commented
消えた？

2016-12-06 06:17 UTC, shundroid commented
消した記憶はない？

2016-12-06 06:17 UTC, mk7087 commented
ない

2016-12-06 06:17 UTC, mk7087 commented
復旧方法ある？

2016-12-06 06:18 UTC, shundroid commented
![2016-12-06_15h17_30](https://cloud.githubusercontent.com/assets/8530218/20915098/1c61eaa4-bbc7-11e6-8ccf-a6a25b860200.png)

ブランチが master と patch-1 だけになってる

作業していたブランチの名前って何？

2016-12-06 06:20 UTC, mk7087 commented
このリポジトリのやってたブランチのこと？

2016-12-06 06:21 UTC, mk7087 commented
5ぐらいだったと思う

2016-12-06 06:21 UTC, shundroid commented
patch から変更履歴を取る方法があるから、それでとりあえず新しいブランチを作ってマージします

2016-12-06 06:23 UTC, shundroid commented
とりあえず、 `develop` ブランチにマージした

2016-12-06 06:23 UTC, closed without merging